### ISSUE TITLE
--no-dereference is not a valid option on FreeBSD

### ISSUE THREAD

**Issue by rick-pri** [GeoffWilliams/puppet-chown_r#2]
I believe that the `-h` option is the same across BSD/POSIX and GNU versions of the `chown` command so this should be used instead.

**Comment by GeoffWilliams** [comment]
fix released in v1.1.1

**Comment by rick-pri** [comment]
Thanks Geoff for such a rapid turn around.  Also, I did work around this by setting `$options` to `-h` but it's always better if the defaults don't break on people and force them to debug why something isn't working as they expect it to :)

Also, you got to this and fixed it before I had time to make a PR so :+1:
