### ISSUE TITLE
/usr/sbin path missing for chown on FreeBSD

### ISSUE THREAD

**Issue by rick-pri** [GeoffWilliams/puppet-chown_r#4]
The location of the `chown` binary on FreeBSD is in `/usr/sbin`.  I've created a PR to fix this [here](https://github.com/declarativesystems/puppet-chown_r/pull/3).

**Comment by GeoffWilliams** [comment]
released v1.1.2

I don't claim to support FreeBSD, but there's no need to actively break it ;-)

**Comment by rick-pri** [comment]
I know, not many do :grin:  but thanks for getting the support merged in.

The advantage of OS software development is that you don't have to do all the work to support all the platforms so long as people like me are willing to extend it to support our use cases (and carry on supporting it in future) so that everyone wins.
